### PR TITLE
Added an Observer Design Pattern

### PR DESCRIPTION
**Pull request by leovaldez08**
- Added a design pattern to optimise the code.
- Added comments to make the code more readable.

Concepts covered for the Milestone - 5: 
I've attached the loom video explanation for the below mentioned concepts.

Templates and Interfaces: [Link](https://www.loom.com/share/f912b4baf5b64a8b8914f287c473bb54?sid=46347f6e-4d72-494b-9994-ec114370f161)
SOLID Principles: [Link](https://www.loom.com/share/04b524b1b3b74f06931d2322f45f4fa2?sid=88533d2b-8e48-4790-87f8-d76f8004ce61)
Design Pattern: [Link](https://www.loom.com/share/1c13e484175f43288791b83e8227b5e1?sid=a9a27a00-1650-4e9e-bde7-832218ebb0c4)

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
thanks @leovaldez08 for you submission - 

1. the explanation for `Templates` provided is not correct. `Templates` is a piece of generic code which can be used by any data type. the example provided (MineSweeper Class) doesn't adhere to that.
2. for `SOLID Principle` you need to mention the various principles but may demonstrate any one in your code. You have explained `three` of the `five` principles.  -- please add video explaining the remaining principles.

thanks

**Review by th3c0d3br34ker — CHANGES_REQUESTED** [review]
thanks @leovaldez08 for you submission -

1. the explanation for `Templates` provided is not correct. A `Template` is a piece of generic code which can be used by any data type. the example provided (MineSweeper Class) doesn't adhere to that.
2. for `SOLID Principle` you need to mention the various principles but may demonstrate any one in your code. You have explained `three` of the `five` principles. -- please add video explaining the remaining principles.

thanks

**Comment by Tharun-kailash** [comment]
Hey Rishi, 
Please book a viva slot in my calendar.
Thanks.

**Comment by Tharun-kailash** [comment]
Viva is done.
Please merge this PR.

**Pull request merged**
